name = "StochasticArithmetic"
uuid = "f771ca10-1b0b-53f6-a01e-a0d756bd6223"
authors = ["François Févotte <fevotte@gmail.com>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
